import { getCollection, type CollectionEntry } from "astro:content";

export type Post = CollectionEntry<"blog">;

/**
 * A post is "published" while it is inside its publish window:
 * `post_hero.date <= now < post_hero.unpublish_date`.
 *
 * - Before `post_hero.date` the post is scheduled — kept out of the build until
 *   a later build runs after its date has passed.
 * - `post_hero.unpublish_date` is optional. When set, the post is removed from
 *   the build once that time has passed; when empty, the post stays published
 *   indefinitely.
 *
 * The build is static, so "now" is frozen at build time. CloudCannon triggers a
 * fresh build at each scheduled date (see `_schedule.txt`, generated by
 * `scripts/generate-schedule.mjs`), so the post goes live at its publish date
 * and drops off the site at its unpublish date, with no manual step.
 */
export function isPublished(post: Post, now: number = Date.now()): boolean {
  const published = new Date(post.data.post_hero.date).getTime() <= now;
  const unpublish = post.data.post_hero.unpublish_date;
  const live = !unpublish || new Date(unpublish).getTime() > now;
  return published && live;
}

/**
 * All published blog posts, newest first. Use this everywhere posts are listed
 * or paged so future-dated posts never leak into the build (index, tags, feed,
 * related posts, and the per-post routes).
 */
export async function getPublishedPosts(): Promise<Post[]> {
  const posts = await getCollection("blog", (post) => isPublished(post));
  return posts.sort(
    (a, b) =>
      new Date(b.data.post_hero.date).getTime() -
      new Date(a.data.post_hero.date).getTime(),
  );
}
